version: '3'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://root:1234@mongo:27017/'
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - '27017:27017'
    volumes:
      - ${PROJECT_PATH}/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

  api:
    container_name: api-container
    image: node:18
    working_dir: ${PROJECT_PATH}/Docker/discord-bot-api
    restart: always
    command: bash -c "npm install --force && npm run debug:docker"
    environment:
      - MONGO_URL=mongodb://root:1234@mongo:27017/
    volumes:
      - ./dist/:${PROJECT_PATH}/Docker/discord-bot-api/dist
      - ./package.json:${PROJECT_PATH}/Docker/discord-bot-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
