version: '3'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://root:1234@mongo:27017/'
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - '27017:27017'
    volumes:
      - /home/rafael/projects/discord-bot-api/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

  api:
    container_name: api-container
    image: node:16
    working_dir: /home/rafael/projects/discord-bot-api/Docker/discord-bot-api
    restart: always
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://root:1234@mongo:27017/
    volumes:
      - ./dist/:/home/rafael/projects/discord-bot-api/Docker/discord-bot-api/dist
      - ./package.json:/home/rafael/projects/discord-bot-api/Docker/discord-bot-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
